In [ ]:
import pandas as pd

df = pd.read_csv("../data/sample.csv") # How simple!! No need for open(), readlines(), or loops!

df.head() # head displays the first 5 rows of the dataframe (table) and just df displays the whole thing.

# df

   id   name  age  score
0   1    Ali   22   14.5
1   2   Sara   24    9.0
2   3   Omar   21   12.0
3   4   Lina   23   18.5
4   5  Tariq   25   15.0

In [4]:
print("--- Dataset Info ---")

df.info() # info() tells the column names, data types, and if any data is missing.

print("\n--- Statistical Summary ---")

df.describe() # describe() instantly calculates the count, mean, min, and max for numeric columns

--- Dataset Info ---
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     str
 2   age     10 non-null     int64
 3   score   10 non-null     float64
dtypes: float64(1), int64(2), str(1)
memory usage: 452.0 bytes

--- Statistical Summary ---

             id        age      score
count  10.00000  10.000000  10.000000
mean    5.50000  22.800000  14.300000
std     3.02765   1.932184   3.433495
min     1.00000  20.000000   9.000000
25%     3.25000  21.250000  11.625000
50%     5.50000  22.500000  14.750000
75%     7.75000  24.000000  16.750000
max    10.00000  26.000000  19.000000

In [ ]:
names = df["name"] # Select a single column (returns a series (1D arrray))

print("--- Just the names---")
display(names.head(3)) # Prints first 3 rows 

subset = df[["name", "score"]]
print("\n--- Names & Score ---")
subset.head(3)

--- Just the names---
0     Ali
1    Sara
2    Omar
Name: name, dtype: str

--- Names & Score ---

   name  score
0   Ali   14.5
1  Sara    9.0
2  Omar   12.0

In [17]:
top_students = df[df["score"] > 14] # Only the students with a score higher than 14
print("--- Top Students ---")
top_students # No print(), to get a nice html table

--- Top Students ---

   id   name  age  score
0   1    Ali   22   14.5
3   4   Lina   23   18.5
4   5  Tariq   25   15.0
6   7   Zayn   22   16.0
7   8   Maya   24   19.0
9  10   Hana   21   17.0