In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

# Simulating a broken dataset extract
data = {
    'student_id': [1, 2, 3, 4, 4, 5], # Notice the duplicate ID 4
    'name': ['Ali', 'Sara', 'Omar', 'Lina', 'Lina', np.nan], # Missing name at the end
    'score': [14.5, 9.0, np.nan, 18.5, 18.5, 15.0], # Missing score in the middle
    'subject': ['Math', 'Math', 'Physics', 'Physics', 'Physics', 'Math']
}

df_messy = pd.DataFrame(data)
print("--- Raw Messy Data ---")
display(df_messy)

--- Raw Messy Data ---

   student_id  name  score  subject
0           1   Ali   14.5     Math
1           2  Sara    9.0     Math
2           3  Omar    NaN  Physics
3           4  Lina   18.5  Physics
4           4  Lina   18.5  Physics
5           5   NaN   15.0     Math

In [9]:
print('--- 1. Dropping Duplicates ---')

df_clean = df_messy.drop_duplicates().copy()
display(df_clean)

print("--- 2. Handling Missing Text (Names) ---")
df_clean["name"] = df_messy['name'].fillna("Unknown") # Replacing missing names with Unknown

print("--- 3. Handling Missing Numbers (Scores) ---")
average_score = df_clean['score'].mean()
df_clean['score'] = df_messy['score'].fillna(average_score) # Replace missing scores with average score

print("--- 4. The final result ---")
display(df_clean)

--- 1. Dropping Duplicates ---

   student_id  name  score  subject
0           1   Ali   14.5     Math
1           2  Sara    9.0     Math
2           3  Omar    NaN  Physics
3           4  Lina   18.5  Physics
5           5   NaN   15.0     Math

--- 2. Handling Missing Text (Names) ---
--- 3. Handling Missing Numbers (Scores) ---
--- 4. The final result ---

   student_id     name  score  subject
0           1      Ali  14.50     Math
1           2     Sara   9.00     Math
2           3     Omar  14.25  Physics
3           4     Lina  18.50  Physics
5           5  Unknown  15.00     Math

In [ ]:
print("--- Average score per subject ---")
subject_stats = df_clean.groupby('subject')['score'].mean().reset_index() # SQL equivalent: SELECT subject, AVG(score) FROM table GROUP BY subject
display(subject_stats)

--- Average score per subject ---

AttributeError: 'Series' object has no attribute 'reset'